### ISSUE TITLE
unable to use library without clear license

### ISSUE THREAD

**Issue by jeremy-w** [BurntSushi/xdg#1]
Hello there!

I hoped a library like this existed out there, so I was very excited when I found yours.

If you would be so kind as to add a LICENSE/COPYING file (might I suggest [the ISC license](http://opensource.org/licenses/isc-license.txt)?), others might then use your library with clear conscience.

Thank you!

---

Example license file:

> Copyright (c) 2013, Andrew Gallant
> 
> Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.
> 
> THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

**Comment by BurntSushi** [comment]
How embarrassing. I've added the WTFPL. Thanks for the heads up!

**Comment by pierreprinetti** [comment]
funny, some license parsers do not recognise WTFPL.

eg pkg.go.dev (uses rsc's tool which knows WTFPL, but pkg.go.dev itself does not include it as a OK license):
https://pkg.go.dev/github.com/BurntSushi/xdg
https://pkg.go.dev/license-policy
