### ISSUE TITLE
Usage when creating new files?

### ISSUE THREAD

**Issue by grawity** [BurntSushi/xdg#2]
The documentation says:

``` go
// ConfigFile returns a file path containing the configuration file
// specified. If one cannot be found, an error will be returned which
// contains a list of all file paths searched.
```

So how would one use these functions when trying to _create_ a configuration or data file, if they always return `""` + error in that case?

**Comment by BurntSushi** [comment]
This package implements the specification for _discovering_ files. Creating them is a different process. Maybe it's a distribution package and the default config goes in `/etc` (which was decided by the package maintainers), or maybe the user has copied the default config from `/etc` into `~/.config`.

Usually I have a `--write-config` option or something similar that will write a fresh config to the user's config directory. Example: https://github.com/BurntSushi/wingo/blob/master/write_config.go#L13-L53 (There may be room for some _helper_ functions in this package though. Like getting the value of `XDG_CONFIG_HOME` even when `XDG_CONFIG_HOME` isn't set.)
